--- #YAML:1.0
name: haver-server
version: 0.051
license: gpl
distribution_type: module
requires:
  Digest::SHA1: 2.01
  Haver: 0.05
  POE: 0.26
  YAML: 0.35
  perl: 5.6.1
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Haver::Server:
    file: lib/Haver/Server.pm
    version: 0.051
  Haver::Server::Channel:
    file: lib/Haver/Server/Channel.pm
    version: 0.02
  Haver::Server::Commands:
    file: lib/Haver/Server/Commands.pm
    version: 0.02
  Haver::Server::Connection:
    file: lib/Haver/Server/Connection.pm
  Haver::Server::Listener:
    file: lib/Haver/Server/Listener.pm
  Haver::Server::Object:
    file: lib/Haver/Server/Object.pm
    version: 0.01
  Haver::Server::Object::Index:
    file: lib/Haver/Server/Object/Index.pm
    version: 0.03
  Haver::Server::Registry:
    file: lib/Haver/Server/Registry.pm
    version: 0.03
  Haver::Server::User:
    file: lib/Haver/Server/User.pm
    version: 0.03
generated_by: Module::Build version 0.21
